[package]
name = "api"
version = "0.1.0"
authors = ["Arjun Patrawala <ajpat1234@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = {version = "0.3.5", default-features = false, features = ["mysql", "runtime-tokio", "macros"]}
actix-web = "2.0.0"
actix-rt = "1.1.1"
serde = "1.0.114"
serde_json = "1.0.56"